name: PHP CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup PHP
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: xdebug
          tools: composer

      # Install dependencies
      - name: Install dependencies
        run: |
          composer clear-cache
          composer install --no-progress --no-suggest
          chmod +x vendor/bin/phpunit  # Memberikan izin eksekusi

      # Jalankan PHPUnit
      - name: Run PHPUnit tests
        run: vendor/bin/phpunit --coverage-text
