name: PHP CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Langkah 1: Checkout kode dari repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Langkah 2: Setup PHP
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'  # Gunakan versi PHP Anda
          extensions: xdebug
          tools: composer

      # Langkah 3: Install dependencies
      - name: Install dependencies
        run: |
          composer clear-cache
          composer install --no-progress --no-suggest

      # Langkah 4: Jalankan PHPUnit
      - name: Run PHPUnit tests
        run: vendor/bin/phpunit --coverage-text

  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Deploy ke server (opsional)
      - name: Deploy to server
        run: echo "Deployment step goes here"
